
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://esrlselsbcpavfsmmida.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzcmxzZWxzYmNwYXZmc21taWRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzODk5NjEsImV4cCI6MjA2NTk2NTk2MX0.mHIh4fmsFuAPVa_NetjOfzTL4FuStxzgOAabiQrvjYk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
